#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
fi

if [ -f /usr/bin/xdg-desktop-menu ]; then
    xdg-desktop-menu install --novendor /usr/share/applications/nightbird.desktop > /dev/null || true
fi


if [ "$1" = "configure" ] ; then
    chmod g+rwX /opt/thunderbird -R
    chgrp users /opt/thunderbird -R
fi
